spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hello_test?useUnicode=true
    username: *****
    password: ******
    driver-class-name: com.mysql.jdbc.Driver
  quartz:
    jdbc:
      initialize-schema: never
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class:  org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass:  org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix:  QRTZ_
            isClustered:  true
            clusterCheckinInterval: 10000
            useProperties:  false
          threadPool:
            class:  org.quartz.simpl.SimpleThreadPool
            threadCount:  10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    auto-startup: true
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.example.demo.entity
logging:
  config: classpath:lockback.xml

